name: Sync Internal Python Docs

# Kills old jobs from the same pr if we push a new commit
# See https://stackoverflow.com/questions/66335225/how-to-cancel-previous-runs-in-the-pr-when-you-push-new-commitsupdate-the-curre
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

# Controls when the workflow will run
on:
  # Triggers the workflow on push requests for the main branch
  push:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  sync-python-docs:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, which is the CWD for
      # the rest of the steps
      - uses: actions/checkout@v2
        with:
          submodules: "recursive"
          token: ${{ secrets.CICD_REPO_ACCESS_TOKEN }}

      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.DOC_HOSTING_EC2_SSH_KEY }}
          name: id_rsa
          known_hosts: ${{ secrets.DOC_HOSTING_KNOWN_HOSTS }}

      - name: Install libcurl dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y curl libssl-dev libcurl4-openssl-dev

      - name: Build Universe
        run: bin/build.py -f THIRDAI_BUILD_LICENSE -e docs

      - name: Build docs
        run: |
          (cd docs/internal_docs && make html)

      - name: Remove current docs
        run: ssh ${{ secrets.DOC_HOSTING_EC2_USERNAME }}@${{ secrets.DOC_HOSTING_REMOTE_SERVER }} "rm -rf /home/ubuntu/html"

      - name: Copy built docs
        run: scp -r docs/internal_docs/_build/html ${{ secrets.DOC_HOSTING_EC2_USERNAME }}@${{ secrets.DOC_HOSTING_REMOTE_SERVER }}:/home/ubuntu/
